### ISSUE TITLE
一加 6T android10 闪退呀 朋友

### ISSUE THREAD

**Issue by liuhuan0225** [LouisDai8409/myCodes#1]

**Comment by LouisDai8409** [comment]
对不起啊，我用的 AS 的 6.0 的模拟器测试的，没有问题。实机没有测试过。因为我的需求也是特定机型指定版本的。您能给我一个日志吗？或者说是在什么时候报错的，是启动都不行，还是开始点击报错，还是停止录制报错的呢

**Comment by LouisDai8409** [comment]
> _No description provided._

对不起啊，我用的 AS 的 6.0 的模拟器测试的，没有问题。实机没有测试过。因为我的需求也是特定机型指定版本的。您能给我一个日志吗？或者说是在什么时候报错的，是启动都不行，还是开始点击报错，还是停止录制报错的呢

**Comment by LouisDai8409** [comment]
> _No description provided._

我重新上传了一下代码，确实我刚才试了一下录制有问题。是因为我加了线程，本来希望是能够减轻主线程在创建VirtualScreen 的压力的，忘记删除了。您可以再下载 试一下，如果还有问题，请您给我贴一下 报错的信息。

**Comment by liuhuan0225** [comment]
感谢你能回复我的邮件，重新拉了一下代码，依旧不行 报错信息如下：点击确定授权之后就会奔溃

2020-08-17 19:54:54.975 28031-28031/com.example.recordscreen E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.recordscreen, PID: 28031
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1002, result=-1, data=Intent { (has extras) }} to activity {com.example.recordscreen/com.rs.activity.MainActivity}: java.lang.SecurityException: Media projections require a foreground service of type ServiceInfo.FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4962)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5003)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2109)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
     Caused by: java.lang.SecurityException: Media projections require a foreground service of type ServiceInfo.FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION
        at android.os.Parcel.createException(Parcel.java:2071)
        at android.os.Parcel.readException(Parcel.java:2039)
        at android.os.Parcel.readException(Parcel.java:1987)
        at android.media.projection.IMediaProjection$Stub$Proxy.start(IMediaProjection.java:231)
        at android.media.projection.MediaProjection.<init>(MediaProjection.java:58)
        at android.media.projection.MediaProjectionManager.getMediaProjection(MediaProjectionManager.java:104)
        at com.rs.service.RecordService.createMediaProjection(RecordService.java:52)
        at com.rs.service.RecordService.prepare(RecordService.java:44)
        at com.rs.util.ScreenRecordUtil.prepare(ScreenRecordUtil.java:61)
        at com.rs.activity.MainActivity.onActivityResult(MainActivity.java:145)
        at android.app.Activity.dispatchActivityResult(Activity.java:8135)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4955)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5003) 
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2109) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7682) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950) 
     Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.media.projection.MediaProjectionManagerService$MediaProjection.start(MediaProjectionManagerService.java:485)
        at android.media.projection.IMediaProjection$Stub.onTransact(IMediaProjection.java:135)
        at android.os.Binder.execTransactInternal(Binder.java:1032)
        at android.os.Binder.execTransact(Binder.java:1005)

**Comment by liuhuan0225** [comment]
我知道大概问题出在哪里  是Android10的适配问题  我也尝试去适配 但是未能如愿，希望可以请教一下 ，我是参考下面的链接https://blog.csdn.net/qq_36332133/article/details/96485285
